from generators.BaseGenerator import BaseGenerator


fileOpener: str = """---@meta
-- Generated by PZEventDoc https://github.com/demiurgeQuantified/PZEventDoc

-- If it helped you, please consider leaving me a tip ^u^
-- https://ko-fi.com/starseamstress
"""


class LuaCATSGenerator(BaseGenerator, extensions=["lua"]):
    def __init__(self, wantDeprecated):
        BaseGenerator.__init__(self, wantDeprecated)
        self.initialisedTables = []
        self.currentIndentation = 0

    def writeLine(self, text: str):
        self.totalString += "    " * self.currentIndentation + f"{text}\n"

    def beginFile(self):
        self.totalString = fileOpener

    @staticmethod
    def getFunctionSignature(params: list[dict] | None) -> str:
        if params is None or len(params) == 0:
            return "function"

        formattedParams = ""
        doComma = False
        for parameter in params:
            if doComma:
                formattedParams += ","
            else:
                doComma = True

            formattedParams += f"{parameter['name']}:{parameter['type']}"

        return f"fun({formattedParams}):any"

    @staticmethod
    def formatFunction(name: str, args: list = None) -> str:
        formattedArgs = ""
        if not (args is None or len(args) == 0):
            formattedArgs = args[0]
            for label in args[1:]:
                formattedArgs += f", {label}"

        return f"{name} = function({formattedArgs}) end,"

    def documentFunction(self, name: str, params: list[dict] = None):
        def writeFuncParam(params: list[dict] | None):
            self.writeLine("---@param func " + self.getFunctionSignature(params))

        writeFuncParam(params)

        self.writeLine(self.formatFunction(name, ["func"]))

    def initTable(self, name: str):
        self.writeLine(name + " = {}")
        self.initialisedTables.append(name)

    def document(self, name: str, data: dict, tableType: str = "Events"):
        deprecated: bool = data.get("deprecated", False)
        if not self.checkAllowDeprecated(deprecated):
            return

        if tableType not in self.initialisedTables:
            self.initTable(tableType)

        if deprecated:
            self.writeLine("---@deprecated")

        self.writeLine("---" + self.getDescription(data.get("notes", ""), deprecated, data.get("context", {})))
        self.writeLine(tableType + "." + name + " = {")
        self.currentIndentation += 1

        self.documentFunction("Add", data.get("callback"))
        self.documentFunction("Remove")

        self.currentIndentation -= 1
        self.writeLine("}")

    def documentHook(self, name: str, data: dict):
        self.document(name, data, "Hook")

    def documentEvent(self, name: str, data: dict):
        self.document(name, data, "Events")
