from eventdoc.rendering.renderers.base_renderer import BaseRenderer

from rosetta.game.projectzomboid.event import ZomboidEvent
from rosetta.lua.callback import LuaCallback


class LuaRenderer(BaseRenderer, extensions=["lua"]):
    def __init__(self):
        """
        Class responsible for generating LuaCATS annotations
        """
        BaseRenderer.__init__(self)
        self.initialised_tables: list[str] = []
        """List of table names that have already been initialised"""
        self.current_indentation: int = 0
        """The current level of indentation"""
        self.total_string = "---@meta\n-- Generated by PZEventDoc https://github.com/demiurgeQuantified\n"

    def write_line(self, text: str):
        """
        Writes a line with the current level of indentation

        :param text: The text to write
        :return:
        """
        self.total_string += "    " * self.current_indentation + f"{text}\n"

    @staticmethod
    def get_function_signature(data: LuaCallback) -> str:
        """
        Returns a function signature type description

        :param data: Rosetta callback definition
        :return:
        """
        if len(data.parameters) <= 0 and len(data.returns) <= 0:
            return "function"

        signature = "fun("

        do_comma = False
        for parameter in data.parameters:
            if do_comma:
                signature += ","
            else:
                do_comma = True

            parameter_type: str = parameter.type
            # remove non-table generics
            if parameter_type.find("<") and not (parameter_type.startswith("table")):
                parameter_type = parameter_type.split("<", 1)[0]

            signature += f"{parameter.name}:{parameter_type}"
        signature += ")"

        if len(data.returns) > 0:
            signature += ":"
            do_comma = False
            for retval in data.returns:
                if do_comma:
                    signature += ","
                else:
                    do_comma = True
                if retval.name != "":
                    signature += f"{retval.name}:"
                signature += retval.type

        return signature

    @staticmethod
    def describe_callback(callback: LuaCallback) -> str:
        description = ""

        if callback.notes != "":
            description = callback.notes + "<br><br>"

        for parameter in callback.parameters:
            if parameter.notes == "":
                continue
            description = description + f"{parameter.name} - {parameter.notes}<br>"

        if len(callback.returns) > 0:
            description + f"<br>Returns:\n"
            for retval in callback.returns:
                description = description + f"<br>{retval.type} {retval.name}"
                if retval.notes != "":
                    description = description + f" - {retval.notes}"

        return description

    @staticmethod
    def format_function(name: str, args: list[str]) -> str:
        """
        Returns an empty function declaration

        :param name: Name of the function to declare
        :param args: List of parameter names
        :return:
        """
        formatted_args = ""
        if not (len(args) == 0):
            formatted_args = args[0]
            for label in args[1:]:
                formatted_args += f", {label}"

        return f"{name} = function({formatted_args}) end,"

    def document_function(self, name: str, callback_type: str):
        """
        Documents a function that takes a single callback argument

        :param name: Name of the function
        :param callback_type: Name of the callback type
        :return:
        """
        self.write_line("---@param callback " + callback_type)

        self.write_line(self.format_function(name, ["callback"]))

    def annotate_callback(self, name: str, data: LuaCallback):
        """
        Documents a function type

        :param name: Name of the type
        :param data: Rosetta formatted list of parameters
        :return:
        """
        self.write_line("---" + self.describe_callback(data))
        self.write_line(f"---@alias {name} {self.get_function_signature(data)}\n")

    def init_table(self, name: str):
        """
        Initialises an empty lua table

        :param name: Name of the table
        :return:
        """
        self.write_line(name + " = {}\n")
        self.initialised_tables.append(name)

    def document(self, data: ZomboidEvent, table_name: str = "Events"):
        """
        Documents an event/hook's callback type and Add/Remove functions

        :param data: Rosetta formatted event/hook data
        :param table_name: Name of the table containing the object (Events/Hook)
        :return:
        """
        if not self.should_render(data):
            return

        if table_name not in self.initialised_tables:
            self.init_table(table_name)

        callback_name = "Callback_" + data.name
        self.annotate_callback(callback_name, data.callback)

        if data.deprecated:
            self.write_line("---@deprecated")

        self.write_line("---" + self.create_description(data))
        self.write_line("---<br><br>" + self.describe_callback(data.callback))

        self.write_line(f"{table_name}.{data.name} = {{")
        self.current_indentation += 1

        self.document_function("Add", callback_name)
        self.document_function("Remove", callback_name)

        self.current_indentation -= 1
        self.write_line("}\n")

    def add_event(self, data: ZomboidEvent):
        """
        Writes documentation for an event

        :param data: Rosetta formatted event data
        :return:
        """
        self.document(data, "Events")

    def add_hook(self, data: ZomboidEvent):
        """
        Writes documentation for a hook

        :param data: Rosetta formatted hook data
        :return:
        """
        self.document(data, "Hook")

    def add_callback(self, name: str, data: LuaCallback):
        """
        Writes documentation for a callback

        :param name: Name of the callback
        :param data: Rosetta callback object
        :return:
        """
        self.annotate_callback(name, data)

    def render(self):
        return self.total_string
